model_params:
  vae_ckpt: './logs/VanillaVAE/version_2/checkpoints/last.ckpt'
  actor_name: 'Actor'
  critic_name: 'Critic'
  name: 'Actor-Critic'
  latent_dim: 1024
  hidden_dim: 2048
  layer_num: 4
  num_label: 10
  num_output: 10

data_params:
  data_path: "../data/"
  train_batch_size: 128
  val_batch_size:  128
  patch_size: 64
  num_workers: 8
  num_labels: 10


exp_params:
  actor_LR: 0.0003
  critic_LR: 0.0003
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265
  latent_dim: 1024
  num_labels: 10

trainer_params:
  gpus: [0]
  max_epochs: 300
  resume_from_checkpoint: '/home/chandramouli/Documents/UCSD-Assignments/ECE-176/ECE176_Project/logs/ACVAE/version_14/checkpoints/last.ckpt'

logging_params:
  save_dir: "logs/"
  name: "ACVAE"