model_params:
  vae_ckpt: '/content/drive/MyDrive/Colab Notebooks/ECE176_PR/PyTorch-VAE/logs/VanillaVAE/version_1/checkpoints/last.ckpt'
  name: 'ACVAE'
  latent_dim: 256
  hidden_dim: 512
  layer_num: 4
  num_label: 10
  num_output: 10


data_params:
  data_path: "/content/drive/MyDrive/Colab Notebooks/ECE176_PR/data/"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 64
  num_workers: 4
  num_labels: 10


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265
  latent_dim: 256
  num_labels: 10

trainer_params:
  gpus: 0
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "ACVAE"
  
