model_params:
  name: 'VanillaVAEMNIST'
  in_channels: 1
  latent_dim: 1024


data_params:
  data_path: "./data/"
  train_batch_size: 32
  val_batch_size:  32
  patch_size: 28
  num_workers: 8
  num_labels: 10


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [0]
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "VanillaVAEMNIST"
  
